# Generated by Django 3.2.8 on 2022-10-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название тега')),
                ('hexcolor', models.CharField(max_length=7, unique=True, verbose_name='цветовой HEX-код')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='слаг')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Тэги',
                'ordering': ['-id'],
            },
        ),
    ]
