# Generated by Django 3.2.8 on 2022-10-18 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='measurement_unit',
            field=models.CharField(help_text='Введите единицу измерения', max_length=100, unique=True, verbose_name='единица измерения'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.CharField(help_text='Введите название ингредиента', max_length=100, unique=True, verbose_name='название ингредиента'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='hexcolor',
            field=models.CharField(help_text='Введите HEX-код тега', max_length=7, unique=True, verbose_name='цветовой HEX-код'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Введите название тега', max_length=100, unique=True, verbose_name='название тега'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Введите слаг', max_length=100, unique=True, verbose_name='слаг'),
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название рецепта', max_length=200, verbose_name='название рецепта')),
                ('text', models.TextField(help_text='Введите описание рецепта')),
                ('image', models.ImageField(blank=True, help_text='Выберите изображение', upload_to='recipes/', verbose_name='картинка')),
                ('cooking_time', models.IntegerField(help_text='Введите время приготовления', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время приготовления')),
                ('ingredients', models.ManyToManyField(help_text='Выберите ингредиенты', to='recipes.Ingredients', verbose_name='Ингредиенты')),
                ('tags', models.ManyToManyField(help_text='Выберите тэги', to='recipes.Tag', verbose_name='Тэг')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ['-id'],
            },
        ),
    ]
