# Generated by Django 3.2.8 on 2022-11-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20221104_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='hexcolor',
            field=models.CharField(choices=[('Red', '#FF0000'), ('Orange', '#FFA500'), ('Yellow', '#FFFF00'), ('Green', '#00FF00'), ('Blue', '#0000FF'), ('Dark blue', '#00008b'), ('Purple', '#A020F0')], help_text='Выберите цветовой HEX-код', max_length=100, verbose_name='цвет тэга'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Введите название тэга', max_length=100, unique=True, verbose_name='название тэга'),
        ),
    ]
