# Generated by Django 3.2.8 on 2022-10-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', help_text='Выберите роль пользователя', max_length=15, verbose_name='Пользовательская роль'),
        ),
    ]
